#!/usr/bin/ruby

require 'colorize'
require 'socket'
require 'awesome_print'
require 'terminal-table'
require 'JSON'
require 'open-uri'


ips = Terminal::Table.new

ips.add_row(["Number", "IP Address"])
ips.add_separator

Socket.ip_address_list.each_with_index do |single, index|
	ip = single.ip_address
	if ip.index("192.168") == 0 
		ip = ip.green
	end
	ips.add_row([index, ip])
end

puts ips

open('http://jsonip.com/') do |f|
	ip = JSON::parse(f.string())["ip"].red
	puts "Public IP Address: #{ip}"
end

